version: "3"

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
      - 33060:33060
    working_dir: /var/lib/mysql
    volumes:
      - mysql:/var/lib/mysql

  ipfs:
    image: ipfs/go-ipfs
    restart: always
    ports:
      - 5001:5001
      - 8080:8080
    volumes:
      - ipfs:/data/ipfs

  minio:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET}
    volumes:
      - minio:/data
    command: server /data --console-address ":9090"

  turbo:
    container_name: turbo
    build:
      context: .
      dockerfile: ./docker/turbo.Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - ipfs
      - minio
    ports:
      - 3000:3000/tcp
      - 3000:3000/udp
      - 4000:4000
      - ${RTC_MIN_PORT}-${RTC_MAX_PORT}:${RTC_MIN_PORT}-${RTC_MAX_PORT}/tcp
      - ${RTC_MIN_PORT}-${RTC_MAX_PORT}:${RTC_MIN_PORT}-${RTC_MAX_PORT}/udp
    volumes:
      - ./apps:/app/apps
      - ./packages:/app/packages

volumes:
  mysql:
  ipfs:
  minio:
