version: "3"

services:
  db:
    image: postgres
    container_name: client-db-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DB_URL=${DB_URL}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}
