version: "3"

services:
  host:
    build:
      context: ../../
      dockerfile: apps/host/Dockerfile
      args:
        - SCOPE=@wired-labs/host
        - RTC_MIN_PORT=${RTC_MIN_PORT}
        - RTC_MAX_PORT=${RTC_MAX_PORT}
    image: host
    container_name: host
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "${RTC_MIN_PORT}-${RTC_MAX_PORT}:${RTC_MIN_PORT}-${RTC_MAX_PORT}/tcp"
      - "${RTC_MIN_PORT}-${RTC_MAX_PORT}:${RTC_MIN_PORT}-${RTC_MAX_PORT}/udp"
    volumes:
      - ./src:/src
