version: "3"

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    ports:
      - "80:80"
    volumes:
      - certbot-var:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
    command: >
      certonly --agree-tos --force-renewal --standalone -d ${HOSTNAME}

  elixir:
    build:
      context: elixir
      dockerfile: Dockerfile
    image: elixir
    container_name: elixir
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
      args:
        - HOSTNAME=${HOSTNAME}
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - certbot-var:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
    depends_on:
      - certbot
      - elixir
    networks:
      - app-network

volumes:
  certbot-etc:
  certbot-var:

networks:
  app-network:
    driver: bridge
