name: CD

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: signaling

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install

      - name: Restart server application
        run: pm2 restart
