name: CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn --prefer-offline --frozen-lockfile

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier
        uses: creyD/prettier_action@v4.2
        with:
          prettier_plugins: "prettier-plugin-prisma prettier-plugin-packagejson"
          prettier_options: --write .
          only_changed: True
          commit_message: "prettier: format files"
          github_token: ${{ secrets.PRETTIER_TOKEN }}
