name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    name: "Prettier"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: "Format"
        uses: creyD/prettier_action@v4.1.1
        with:
          prettier_options: --write .

  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: "Set up node"
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: "Install"
        run: yarn install

      - name: "Build"
        run: yarn build
