name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: creyD/prettier_action@v4.1.1
        with:
          prettier_options: --write **/*.{js,jsx,ts,tsx,md}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - run: yarn install
      - run: yarn lint
      - run: yarn build
